/***********************************************************************/
/*                                                                     */
/*  FILE        :renesas_uvga.c                                        */
/*  DATE        :Wed, Jun 24, 2009                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
                  


void main(void)
{
	
}
